#!/usr/bin/env node
/**
 * Regenerates this playground's synced pages + `docs/.vitepress/config.mjs` by syncing every
 * repo listed in `spec-hub.config.yaml` (design.md Decision 8) straight from GitHub, entirely
 * in memory (`GitHubApiContentSource`, no `git` clone, no temp directory). Run before
 * `vitepress dev`/`vitepress build` — unlike rspress's virtual `addPages` hook, vitepress
 * routing is file-based, so there's no way to skip this step (see
 * `@luhanxin/spec-hub-vitepress-plugin`'s `write-pages.ts` header comment).
 *
 * Invoked automatically by `predev`/`prebuild` in package.json — not meant to be run standalone
 * except for debugging.
 *
 * Shows a live `cli-progress` bar while syncing (skipped when stdout isn't a TTY, e.g. in CI
 * logs, where a redrawing bar would just be noise) — driven by `loadAndSyncRegistry`'s
 * `onProgress` hook (`@luhanxin/spec-hub-core`), which is itself UI-library-agnostic; this
 * script is the one place that turns those plain events into an actual terminal bar.
 */
import {mkdirSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {loadAndSyncRegistry} from '@luhanxin/spec-hub-core';
import {writeSpecHubVitepressPages} from '@luhanxin/spec-hub-vitepress-plugin';
import cliProgress from 'cli-progress';

const playgroundDir = dirname(dirname(fileURLToPath(import.meta.url)));
const configPath = join(playgroundDir, 'spec-hub.config.yaml');
const docsRoot = join(playgroundDir, 'docs');

async function main() {
  const bar = process.stdout.isTTY
    ? new cliProgress.SingleBar(
        {
          format: 'Syncing repos |{bar}| {percentage}% | {value}/{total} | last: {repo}',
          hideCursor: true
        },
        cliProgress.Presets.shades_classic
      )
    : undefined;
  let barStarted = false;

  const repos = await loadAndSyncRegistry(configPath, {
    onProgress: ({identity, status, total}) => {
      if (!bar) return;
      if (!barStarted) {
        bar.start(total, 0, {repo: ''});
        barStarted = true;
      }
      if (status === 'succeeded' || status === 'failed') {
        bar.increment(1, {
          repo: `${identity.org}/${identity.repo}${status === 'failed' ? ' (failed)' : ''}`
        });
      }
    }
  });
  bar?.stop();

  for (const {identity, content} of repos) {
    console.log(
      `Synced ${identity.org}/${identity.repo}: ${content.capabilities.length} capabilities, ` +
        `${content.archivedChanges.length} archived changes, readme: ${content.readme ? 'yes' : 'no'}.`
    );
  }

  const {sidebar} = await writeSpecHubVitepressPages({repos, docsRoot});

  mkdirSync(join(docsRoot, '.vitepress'), {recursive: true});
  writeFileSync(
    join(docsRoot, '.vitepress', 'config.mjs'),
    [
      '// Generated by scripts/sync.mjs — do not edit by hand, re-run `pnpm sync` instead.',
      'export default {',
      "  title: 'lhx-spec-hub playground (vitepress)',",
      `  description: 'Live preview of writeSpecHubVitepressPages rendering ${repos.length} repos synced straight from GitHub',`,
      // Embedded READMEs are verbatim content from outside this package's control and commonly
      // contain repo-relative links (e.g. `./packages/foo`) that are meaningful on GitHub but
      // don't resolve to any page in this generated site — vitepress's default dead-link check
      // would otherwise fail the whole build over that, not just warn.
      '  ignoreDeadLinks: true,',
      `  themeConfig: {sidebar: ${JSON.stringify(sidebar)}}`,
      '};',
      ''
    ].join('\n')
  );

  console.log(`Wrote playground pages + sidebar config under ${docsRoot}`);
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
